from __future__ import annotations

QILT_FOLDER_NAME = "QILT"
ABS_FOLDER_NAME = "ABS"
ABS_EXTRAS_FOLDER_NAME = "Extras"
ABS_EXTRAS_FOLDER_KEY = "ABS_EXTRAS"

QILT_FOLDER_ALIAS = "qilt"
ABS_FOLDER_ALIAS = "abs"
ABS_EXTRAS_FOLDER_ALIAS = "abs_extras"

QILT_2024_GOS_SOURCE = "QILT-2024-GOS"
QILT_2024_GOS_L_SOURCE = "QILT-2024-GOS-L"
